{
 "title": "ODP - Sample",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "sysplex_name",
    "label": "Sysplex Name",
    "query": {
     "query": "label_values(ascpuutil_cpu_percent,sysplex_name)"
    }
   },
   {
    "name": "top_cpu_jobs",
    "label": "Job Name",
    "query": {
     "query": "query_result(topk(20, sum_over_time(ascpuutil_cpu_percent{sysplex_name=~\"$sysplex_name\"}[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total # of Address Spaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ascpuutil_cpu_percent{sysplex_name=~\"$sysplex_name\"})"
    }
   ]
  },
  {
   "title": "Average Delay Percentage by WLM Class",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, avg by (class_name) (km5wlmclpx_total_delay_percent{class_name!=\"undefined\",sysplex_name=~\"$sysplex_name\"}))",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "CPU Percent by Job Name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ascpuutil_cpu_percent{sysplex_name=~\"$sysplex_name\",job_name=~\"$top_cpu_jobs\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Transaction Rate by Workload",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workload_name) (km5wlmclpx_transaction_rate{workload_name!=\"undefined\",workload_name!=\"\",sysplex_name=~\"$sysplex_name\"})",
     "legendFormat": "{{workload_name}}"
    }
   ]
  },
  {
   "title": "Common Storage in use (percentage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (m5stgcdth_percentage_csa_in_use{sysplex_name=~\"$sysplex_name\"})",
     "legendFormat": "CSA"
    },
    {
     "expr": "sum (m5stgcdth_percentage_ecsa_in_use{sysplex_name=~\"$sysplex_name\"})",
     "legendFormat": "ECSA"
    },
    {
     "expr": "sum (m5stgcdth_percentage_sqa_in_use{sysplex_name=~\"$sysplex_name\"})",
     "legendFormat": "SQA"
    },
    {
     "expr": "sum (m5stgcdth_percentage_esqa_in_use{sysplex_name=~\"$sysplex_name\"})",
     "legendFormat": "ESQA"
    }
   ]
  },
  {
   "title": "Total Service Units per second by workload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (workload_name) (km5wlmclpx_total_sus_second{workload_name!=\"undefined\",workload_name!=\"\",sysplex_name=~\"$sysplex_name\"})",
     "legendFormat": "{{workload_name}}"
    }
   ]
  }
 ]
}